version: '2'
services:
  nginx:
    image: prooph/nginx:www
    ports:
        - "8080:80"
        - "443:443"
    links:
      - php:php
    volumes:
      - .:/var/www

  php:
    image: prooph/php:7.1-fpm
    links:
      - mariadb:mariadb
    volumes:
      - .:/var/www

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=cargo_sample

  adminer:
    image: adminer:4.3
    ports:
      - 8081:8080
